JsonFile       <-    Value+
Value          <-    Spacing* (Dictionary / Array / Text / Float / Integer / Boolean) Spacing* / ',' Value
Dictionary     <-    '{' KeyValuePair+ '}'
Array          <-    '[' Value* ']'
KeyValuePair   <-    Spacing* Text ':' Value / (',' KeyValuePair)
Text           <-    '"' (!'"' .)* '"'
Integer        <-    [0-9]+
Float          <-    [0-9]* '.' [0-9]*
Boolean        <-    'true' / 'false'
Spacing        <-    [ \t\n\r]+
