Preprocessor <- (LineComment / BlockComment / Text / Junk / MoreJunk)+


TranslationUnit <- Statement+ EndOfFile?

Statement           <-      Spacing (Expression ';' / File)

File                <-       Text / Scope / Statement / Identifier/ Junk / MoreJunk
LineComment         <-      '//' (!EndOfLine .)* EndOfLine
BlockComment        <-      '/*' (!'*/' .)* '*/'
Text                <-      Quote (!Quote .)* Quote
Scope               <-      '{' (Scope / File) '}'

#Block              <-      '(' ((![(){};] .)+ / Block)* ')'

#FunctionDef        <-      Type? Identifier ('::' Identifier)? Spacing* '(' FunctionArgument* ')' (Spacing* 'const')? (![{};] .)+ Scope
#FunctionArgument   <-      Type Identifier?

Expression          <-      Type Identifier

Type                <-      ((Spacing 'const' Spacing)? Identifier ('::' Identifier)? (Spacing / '*' / '&' / Spacing 'const' Spacing)+)+
Variable            <-      Type Identifier
Identifier          <-      [a-zA-Z_] [a-zA-Z_0-9]* Spacing*
Spacing             <-      (LineComment / BlockComment / [ \t\n\r] / EndOfLine)+
EndOfLine           <-      !'\\' ('\r\n' / '\n' / '\r')
Quote               <-      !'\\' '"'
Junk                <-      (![a-zA-Z_{}"/*:()] .)+ Spacing*
MoreJunk            <-      .
EndOfFile           <-      !.
