
XmlFile    <- XmlStartTag? TagPair+
XmlStartTag <- junk* '<?xml' (!'?>' .)+ '?>'
TagPair    <- tag TagPair* endTag?
tag        <- junk* Tag junk*
Tag        <- '<' Identifier (spacing* Attribute spacing*)* '/'? '>'
endTag     <- junk* EndTag junk*
EndTag     <- '</' Identifier '>'

Attribute  <- Identifier '=' value
value      <- '"' Value '"'
Value      <- (!'"' .)*
spacing    <- [ \t\n\r]+
Identifier <- [a-zA-z:]+
comment    <- '<!--' (!'-->' .)* '-->'
junk       <- (![</>] .)+ / comment
